version: '3.9'

services:
  server:
    image: express-server:v1
    container_name: ts
    networks:
      - testnet
    attach: false
    env_file:
      - .env
    ports:
      - 3000:3000

networks:
  testnet:
    name: testnet
    external: true
